apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sourceoftruth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admondtamang/dotfiles.git
    targetRevision: HEAD
    path: sourceoftruth
  destination:
    server: https://kubernetes.default.svc
    namespace: sourceoftruth
