networks:
  app:
    external: true

services:
  app-prod:
    image: "app-web:prod"
    restart: always
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=production"
      - "traefik.http.routers.web.rule=Host(`app.admondtamang.com.np`)"
