services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /etc/docker/test-mysql:/etc/mysql/conf.d
      - ./mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
