apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: default
  labels:
    app: go-server-deployment
spec:
  selector:
    matchLabels:
      app: go-server-deployment
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-server-deployment
    spec:
      containers:
        - name: go-server-deployment
          image: edr3x/go-chi-server:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myjob
  namespace: default
spec:
  selector:
    app: go-server-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
